name: Docker pull

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: enricoferro/docker-openpvn
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: build the image
      run: |
        docker buildx build \
          --tag $IMAGE_NAME:latest \
          --output=type=registry \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
